### ISSUE TITLE
Works only in editor

### ISSUE THREAD

**Issue by DataGreed** [doomlaser/DepthMask-Unity-Shader#1]
Does not work in game window

**Comment by TerranTian** [comment]
+1

**Comment by doomlaser** [comment]
Try setting the clear flags of your camera to a Solid Color. Something's changed in Unity 2018.x to make this a little wonky. I'll look into it, but changing the clear flags of the camera you need for geometry should help in a pinch

**Comment by doomlaser** [comment]
Try the updated shader?

**Comment by vorrin** [comment]
Hello! I'm having this same issue, on 2021.3 ,with the latest version of the shader, camera is set to clear on skybox (solid colour just works, meaning it shows you a solid colour, which is not what I want here), rendering path is forward and we're using builtin RP. Any ideas on what might be going wrong? 
Thanks!
